### PR TITLE
Settings - initial settings with corresponding commands

### PR DESCRIPTION
**Pull request by aliasfalse**
Feel free to make suggestions about cleanups or something. So far it seems to be working on a fresh DB for me, I haven't tested it on an existing yet.

### CODE REVIEW

**Comment by nspacestd** [comment]
Do the new files have windows-style or unix-style line endings?

**Comment by aliasfalse** [comment]
All new files have unix style

**Comment by aliasfalse** [comment]
@nspacestd what are your thoughts?

**Comment by aliasfalse** [comment]
gonna close this, i think i've got everything moved to #46

**Pull request closed without merging**
